### ISSUE TITLE
AtomicDEX-desktop wont load assets[BUG]:  Says loading, please wait the whirly circle Enabling assets....

### ISSUE THREAD

**Issue by Jabezjnissi** [KomodoPlatform/atomicDEX-Desktop#1191]
**Describe the bug**
After typing in user and password atomicDEX-desktop says loading assests, please wait.  Whirly circle Enabling assets...
atomicDEX never loads.  

I have uninstalled and reinstalled the program but it never load on MacBook Pro.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
![Image 2021-08-13 at 1 52 PM](https://user-images.githubusercontent.com/87051844/129417391-2485af5e-4149-4f69-9f47-925b3d29bb9d.jpg)

**Comment by smk762** [comment]
Can you please send a copy of logs to KMD team in Discord #support channel?
This could be because:
- a zombie mm2 process is still running (a reboot will fix this)
- there is a port conflict (something else on your PC is using the mm2 port)
- there is an issue of connectivity between your PC and electrums (try using mobile wifi, or running with/without VPN)
- coin configs have been corrupted (you can do a manual reset by deleting the coins file for the account you are logging in to)

**Comment by Jabezjnissi** [comment]
I am happy to assist with more instructions. I am in no way a techie person. I do not know what logs your referring to. Where would I look?

FYI I have rebooted computer MacBook Pro and no change along with tried running with a VPN and without no change.

What is a coin configuration and where do I find it? I research a mm2
Port as I don’t know what that is either.

Appreciative of the help

**Comment by Jabezjnissi** [comment]
I have an account with Discord but without an invitation i am unable to locate the KMD #suppoort channel.  Kind regards,

**Comment by Jabezjnissi** [comment]
Found  a link to the Discord.

**Comment by Milerius** [comment]
> Found a link to the Discord.

You can contact me on discord, in #atomicdex-desktop Slyris#2880

**Comment by Milerius** [comment]
solved
