### ISSUE TITLE
[BUG]: DEX fees for SLP tokens should be only taken from BCH balance

### ISSUE THREAD

**Issue by damascene** [KomodoPlatform/atomicDEX-Desktop#1231]
After I did a swap involving a test SLP token, I noticed that fees are taken from the SLP token and from BCH. This is an issue as like Ethereum, BCH network can hold thousands of tokens without having a known value. 
In the screen shot 12.8 sTST token was taken as a fee. With some tokens one token could worth 1 USD or 1000 USD which will make the fees irrational.

**To Reproduce**
Do a swap using sTST slp test coin. You see fees taken from the token not BCH.

**Expected behavior**
Fees should be taken from BCH only as no way to determine the price of most SLP tokens.

**Screenshots**
![image](https://user-images.githubusercontent.com/411046/131454596-e05d4ee1-273a-461a-abee-ec2870ac87fd.png)

**Desktop (please complete the following information):**
APP: 0.5 beta
MM: 2.1.4027_mm2.1-slp-swap_2aae2b680_Linux_Release
Qt: 5.15.2

**Comment by Milerius** [comment]
Sorry i do not understand where is the bug here the taker fee is always in the concrete coin, here `sTST`, and transactions fees are paid in `tBCH`, the parent chain of `sTST` as written in the `coins` cfg file.

> In the screen shot 12.8 sTST token was taken as a fee

Yes, you are swapping 9987 sTST, `9987/777` -> 12.85...

> Fees should be taken from BCH only as no way to determine the price of most SLP tokens.

for the taker fee, it's the taker coin that is used for the moment, so in this case `sTST`

note that SLP integration is not finished yet too, and feedback are more than welcome.

**Comment by damascene** [comment]
Thank you for responding. Didn't know about the 0.13% fee before. I suggest you show a tooltip near the fee display so people can know what it was spent for.
