### ISSUE TITLE
[BUG]: Bestorders doesnt indicate where ERC / BEP variant

### ISSUE THREAD

**Issue by smk762** [KomodoPlatform/atomicDEX-Desktop#1326]
**Describe the bug**
In the bestorders table, most coins are only listed once. 
In the case of coins like BTC which also have a BTC-BEP variant, both are listed as "BTC", and user can't tell if it is BEP20 or not until clicking on the line and checking the form.

**To Reproduce**
1. Go to DEX page
2. Look at bestorders
3. See 2 BTC entries
4. Click on entries to see if BEP20 or not.

**Expected behavior**
BTC-BEP20 is listed as such in the bestorders table (and same for others like ETH-BEP20 etc)

**Screenshots**
![image](https://user-images.githubusercontent.com/35845239/134303431-53db1ff5-119b-4ab1-80d0-9396bc9f703e.png)

**Comment by smk762** [comment]
With segwit integration, this will also need to be handled.
Coins file has `BTC`, `BTC-segwit`, `BTC-BEP20` etc.

**Comment by tonymorony** [comment]
BTC, BTC-segwit - for segwit option it's fine to show only ticker since it's possible to match segwit order with legacy balance and vice versa and also BTC and BTC-segwit got the same orderbook

For tokens (BEP20, ERC20, ...) there is a separate orderbook and you can't match BTC-BEP20 order with BTC balance so indication is needed

**Comment by smk762** [comment]
yep - group BTC/BTC-segwit under "BTC", display others with protocol.
