### ISSUE TITLE
[BUG]: orders don't show...

### ISSUE THREAD

**Issue by ciumete** [KomodoPlatform/atomicDEX-Desktop#1374]
**Describe the bug**
can't see all orders , in bottom side disappear ...

**To Reproduce**
1. Go to DEX -> Orders tab
2. Click on Filter, chose 2 assets who have over 35 orders
3. Scroll down to bottom

**Expected behavior**
Showing all orders

**Screenshots**
![image](https://user-images.githubusercontent.com/4376271/137277237-1257d2f9-8fee-45c0-b406-8bd6ecc54c2a.png)

**Desktop (please complete the following information):**
 - OS: Win 10 Pro x64

**Comment by smk762** [comment]
This seems to be the "fade in effect" not progressing. It does not occur for me looking at history or orders using filter
I can confirm it happens when adding numerous orders in pro view in the same session - later placed orders will progressively fade as their rows are added - but all appear as expected with working fade effect when switching to another page and then back.

**Comment by smk762** [comment]
closing, issue is stale and appears to have been resolved
