### ISSUE TITLE
[BUG]: Themes rework feedback

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Desktop#1383]
cf: https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/1357

will accumulate feedback on this issue

1) we should keep columns background on scroll 

![Screenshot 2021-10-28 at 16 40 47](https://user-images.githubusercontent.com/24797699/139230828-187e6fbe-2a37-417c-9501-ef7da0eb42d6.png)

**Comment by SylEze** [comment]
> > > also, did you remove the light/dark theme switch button from the top panel on purpose or is it a bug?
> > 
> > 
> > Yeah I removed it on purpose, I'm sure I mentionned it somewhere
> > I found it illogical to have a switch between 2 themes when you can have more than 2 themes in the application
> 
> we discussed it a long time ago and decided to make it visible for themes which got pair
> 
> e.g. right now it's only light/dark, but in the future, it might be binance light/dark, xxxx light/dark
> 
> I think it's a good button to have, maybe just a bit of additional logic behind is needed
> 
> The idea is: you enable "atomicdex" theme and then can switch between dark/light by this button if there are atomicdex_dark.json atomicdex_light.json then you switch to let's say "binance" if there is only binance_dark.json and no binance_light.json this button should not be displayed
> 
> Does it have the sense to you?

Okay, let's do this

**Comment by Canialon** [comment]
DEX -> simple -> pick a coin,  have some visual bugs:
pink - search don't match Figma design 
yellow - different distances between context and window frame

![image](https://user-images.githubusercontent.com/77272165/139679769-9f18a60b-a060-45c2-97e0-a85c81208a73.png)

And the hover effect is not working properly
![image](https://user-images.githubusercontent.com/77272165/139820864-b4ade629-d6c8-411a-891d-cfe9ccde63bb.png)

These buttons haven't hover effect:
![image](https://user-images.githubusercontent.com/77272165/139826688-1e78220a-6ce6-4602-bc3c-5a2c24522044.png)

Pink - there is no text on the "maximum" button if the user has not selected a coin. It will be nice if this button appears only after the user selects a coin.
Yellow - a similar problem. This field cannot be used if the user has not selected a coin.  But visually it is not clear. It must be shown that text entry is not possible until the user selects a coin for a swap.
![image](https://user-images.githubusercontent.com/77272165/139833847-c594a23c-94f3-4878-a961-e0452a564324.png)

If you hover over the "clear" icon, an inscription appears that is very difficult to read
![image](https://user-images.githubusercontent.com/77272165/139827227-08e9dbed-35c9-4108-ba90-15bd198ca195.png) 

The hover effect is used for text only, not for icons in the left sidebar. And when you are in the DEX tab, there is no hover color effect.
![image](https://user-images.githubusercontent.com/77272165/139831124-cb2351b0-ccb3-4116-ae01-5ea67cbb9647.png)

Pink - what do you think about removing the tab title on hover when you are on the DEX tab? I think this creates visual noise.
Green - the active tab effect touches the screen (monitor) limit
![image](https://user-images.githubusercontent.com/77272165/139837070-db9a15c7-1478-416c-9c89-0b64f26ec4af.png)

**Comment by Canialon** [comment]
I don't quite get this bug. The normal hover effect for this item is the appearance of a fiat price. But if you hover the cursor at a certain speed, the field will not change.
https://user-images.githubusercontent.com/77272165/140067097-0d755f97-d7a7-49b4-8bff-c35ea512e617.mp4


Wallet -> any coin -> send
The "Address Book" link is too small in comparison with  other text/buttons/links
Impossible to change the amount to send after checking  "max amount". It looks like a feature
![image](https://user-images.githubusercontent.com/77272165/140074503-59d9375f-7fb2-41ff-bd56-ba6b1ee96851.png)


It would look better if this text disappears when the user is on the DEX tab, because it is really small and looks messy, I guess
![image](https://user-images.githubusercontent.com/77272165/140282393-ea7ce4b4-c653-415a-a6a9-5bf9cad3fb88.png)

If you click on any asset in the "portfolio" tab, the "wallet" tab actually opens. But this is not shown on the left sidebar and the tab did not automatically switch. After those steps, you cannot go to the "portfolio" tab. Because you first need to manually switch the tab to "wallet". Video:
https://user-images.githubusercontent.com/77272165/140309172-5dd2b044-6e65-4a7c-9817-c8a4587f07d2.mp4
The same problem (wallet -> any coin -> swap = opening DEX tab):
https://user-images.githubusercontent.com/77272165/140388843-993ebd47-2a61-43d6-9bc7-1602330b016f.mp4

At the "enable assets" window the coins icon and name are too close to each other. Would be better to add some distance between them~
![image](https://user-images.githubusercontent.com/77272165/140319498-e1211fbe-991c-4a0c-a9cc-632f58b0f863.png)

The list of currencies is really long :(
![image](https://user-images.githubusercontent.com/77272165/140389566-da3d3b42-a0a5-4e46-876d-0019be025a62.png)

All lists for selection have the same problem and don't  match figma(
https://user-images.githubusercontent.com/77272165/140391145-e6ac1b88-c25b-4a5c-adb5-147812a2bdb0.mp4

**Comment by SylEze** [comment]
> Green - the active tab effect touches the screen (monitor) limit
> ![image](https://user-images.githubusercontent.com/77272165/139837070-db9a15c7-1478-416c-9c89-0b64f26ec4af.png)

Fixed in 4aadded206bd2e22976462aa303169a0e0ef0a5d

**Comment by SylEze** [comment]
> It would look better if this text disappears when the user is on the DEX tab, because it is really small and looks messy, I guess
> ![image](https://user-images.githubusercontent.com/77272165/140282393-ea7ce4b4-c653-415a-a6a9-5bf9cad3fb88.png)

Fixed in 27f3232094b57712762111907891f480732a6b5b

**Comment by SylEze** [comment]
> If you click on any asset in the "portfolio" tab, the "wallet" tab actually opens. But this is not shown on the left sidebar and the tab did not automatically switch. After those steps, you cannot go to the "portfolio" tab. Because you first need to manually switch the tab to "wallet". Video:
> https://user-images.githubusercontent.com/77272165/140309172-5dd2b044-6e65-4a7c-9817-c8a4587f07d2.mp4
> The same problem (wallet -> any coin -> swap = opening DEX tab):
> https://user-images.githubusercontent.com/77272165/140388843-993ebd47-2a61-43d6-9bc7-1602330b016f.mp4

Fixed in https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/1411

**Comment by SylEze** [comment]
> At the "enable assets" window the coins icon and name are too close to each other. Would be better to add some distance between them~
> ![image](https://user-images.githubusercontent.com/77272165/140319498-e1211fbe-991c-4a0c-a9cc-632f58b0f863.png)

I do not have that issue, can you retry on `dev` please ?

<img width="220" alt="Capture d’écran 2021-11-08 à 12 26 06 PM" src="https://user-images.githubusercontent.com/14373103/140734024-659196dd-c257-452a-ac14-e973ed0726f6.png">

**Comment by tonymorony** [comment]
notifications shouldn't be grey I think. @polevin could you please advise on that?

![image](https://user-images.githubusercontent.com/24797699/140740024-2d77035e-7424-4918-a5cc-5391c42a0d47.png)

**Comment by Canialon** [comment]
> > At the "enable assets" window the coins icon and name are too close to each other. Would be better to add some distance between them~
> > ![image](https://user-images.githubusercontent.com/77272165/140319498-e1211fbe-991c-4a0c-a9cc-632f58b0f863.png)
> 
> I do not have that issue, can you retry on `dev` please ?
> 
> <img alt="Capture d’écran 2021-11-08 à 12 26 06 PM" width="220" src="https://user-images.githubusercontent.com/14373103/140734024-659196dd-c257-452a-ac14-e973ed0726f6.png">

This is repeated on Windows OS

**Comment by tonymorony** [comment]
chart in light theme is dark:

<img width="1438" alt="Screenshot 2021-11-09 at 15 25 36" src="https://user-images.githubusercontent.com/24797699/140888610-f3d9436b-13e7-4152-afbd-76bcf8aaa372.png">

**Comment by SylEze** [comment]
> The hover effect is used for text only, not for icons in the left sidebar. And when you are in the DEX tab, there is no hover color effect. ![image](https://user-images.githubusercontent.com/77272165/139831124-cb2351b0-ccb3-4116-ae01-5ea67cbb9647.png)

Fixed in https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/1418/commits/bcfc3c0b734b4ea7a3734606806e3783b54e742f

**Comment by tonymorony** [comment]
> notifications shouldn't be grey I think. @polevin could you please advise on that?

upd: two options for design were added to figma (personally pref single line option)

![image](https://user-images.githubusercontent.com/24797699/141423360-1ea8d8e1-cb70-415d-8798-da965ed5faeb.png)

**Comment by SylEze** [comment]
> > > At the "enable assets" window the coins icon and name are too close to each other. Would be better to add some distance between them~
> > > ![image](https://user-images.githubusercontent.com/77272165/140319498-e1211fbe-991c-4a0c-a9cc-632f58b0f863.png)
> > 
> > 
> > I do not have that issue, can you retry on `dev` please ?
> > <img alt="Capture d’écran 2021-11-08 à 12 26 06 PM" width="220" src="https://user-images.githubusercontent.com/14373103/140734024-659196dd-c257-452a-ac14-e973ed0726f6.png">
> 
> This is repeated on Windows OS Sorry, I will indicate the operating system

This is now fixed in `design_tweaks` branch by 21a2f65f1e0a8a6f63a480deb698fb1517781be6

**Comment by SylEze** [comment]
> The list of currencies is really long :(
> ![image](https://user-images.githubusercontent.com/77272165/140389566-da3d3b42-a0a5-4e46-876d-0019be025a62.png)

Fixed in `design_tweaks` by aef9298ac243d00811c73ccefc38e599abc541ec
