### ISSUE TITLE
[BUG]: Wallet login validation has extraneous text

### ISSUE THREAD

**Issue by smk762** [KomodoPlatform/atomicDEX-Desktop#1431]
**Describe the bug**
When entering incorrect password, the validation error messages include items only required for initial wallet password creation.

**To Reproduce**
1. Load app
2. Select a wallet to login
3. Enter incorrect password
4. See extraneous validation error messages

**Expected behavior**
A single error message should be shown in red: `incorrect password`

**Screenshots**
![image](https://user-images.githubusercontent.com/35845239/141936389-d1ce99b6-abf8-401c-88a6-36180d5e3c36.png)

**Comment by tonymorony** [comment]
I'm not able to reproduce this one on the latest dev - there is no indication when I input not correct password and press connect (which is also a bug)
@smk762 Could you please clarify on which commit this problem is actual?

On the latest release (0.5.3) it seems to work correctly - icon and field became red on not correct password login try

**Comment by smk762** [comment]
I get same on latest `dev`: button disabled until all criteria (length, capital, special chat) is met.
Same for latest `design_tweaks` and `fix_suffix_form` builds. 

None of the above show any visual feedback on bad password (different bug) like the red outline / shake effect seen in last release.

I'll keep an eye out and see if I can catch this one again, but current state seems to be unaffected.

**Comment by tonymorony** [comment]
thank you for the clarification 👍

I think we should return back red outline/shake effect and in parallel, it can be checked if there is a place in code that can produce pb as on your screenshot
