### ISSUE TITLE
[BUG]: best orders view erroneous

### ISSUE THREAD

**Issue by ca333** [KomodoPlatform/atomicDEX-Desktop#2122]
- doesnt seem checking the vols available against the actual orders
- results in some "rng number"... 
- tested with various pairs including ARRR/KMD

**Comment by smk762** [comment]
This appears to be due to a lack of appropriate visual feedback to user to let them know why values are changing. The simple view changes the amounts input to match the  "best order" selected, which sometimes means setting it lower as there is less on offer from seller. 

An example of how this is communicated in webdex is in the video below
https://user-images.githubusercontent.com/35845239/205017272-daeb2087-8c78-4a2f-be21-852b7cef66b5.mp4

I'll start working on implementing similar visual feedback in Desktop simple view

**Comment by ca333** [comment]
thanks for clarification
