### ISSUE TITLE
Display API errors in GUI

### ISSUE THREAD

**Issue by SirSevenG** [KomodoPlatform/atomicDEX-Desktop#226]
As of now API errors are written in logs with no hint/display in UI.
Sometimes users get confused without proper information, like swaps not starting and/or orders disappearing when there is legit explanation, returned by API in error message.

AE: when trading MAX balance, due to dex fees, quite common API error is `balance X is too low, required Y`. Yet, user will only see swap not starting/disappearing from UI.

**Comment by SirSevenG** [comment]
Also it might be right time to return to this: https://github.com/KomodoPlatform/atomicDEX-API/issues/550

So error messages will make more sense for common users.

**Comment by tonymorony** [comment]
Yes, we need to display in GUI all errors returning by API (on mobile it displaying on bottom in small red panel on the bottom) so user is always aware if something is wrong and can share error text with support

**Comment by naezith** [comment]
That #24 is different. That's about some backend functions not filling the error field even if there is error. @tonymorony

**Comment by tonymorony** [comment]
Oh ok, common goal is the same anyway  (display all MM2 errors in GUI) so we can keep single issue I think just split it on two parts:

 a) forward error from backend RPC wrapper
 b) if error is forwarded display it

**Comment by tonymorony** [comment]
In general I think we can postpone it until errors are standartized on API side (https://github.com/KomodoPlatform/atomicDEX-API/issues/550)

As soon as API will return something like "result": "error" or "result" : "success" it'll be super trivial to display errors

**Comment by naezith** [comment]
I'm thinking about using the same **Log Modal** that we used for **Recover Funds**.

**Comment by tonymorony** [comment]
@naezith I think little red popup on the bottom as on mobile might be fine as well

from another side modal gives user a time to look on error message as long as user want and copy it to the cliboard to share with support, so yeah - same modal sounds good in general.

**Comment by naezith** [comment]
Then I'll try to combine both. Red pop-up will open the modal on click.

**Comment by naezith** [comment]
Feature is ready at #255. Now I need to check every single API call and use it for the ones which have error.

**Comment by naezith** [comment]
I reviewed all the API functions front-end calls. If I am not mistaken, there is only one which has a message in it, that is `recover_fund`. And we already display the `raw_result` of that in a modal. So currently there isn't any API log that I can display. Please make sure my back-end error handling review is correct @Milerius. I need to be notified when any of these changes, I'll modify the front-end accordingly. 

I don't know what is the best implementation but we can have a structure like:

```
{
  "status": 0 / 1, (enum values for success/error or something else)
  "error_id": 124, (enum value instead of English text, so errors can be localized, this ID and the text can be displayed in the toast which appears at bottom when error happens for example) 
  "raw_result": "...API log dump...", (this will be shown at the details modal if user clicks on the error toast)
  "data": { } / "this part has the real result" / true / 31
}
```

Here is my review:

# Does have error
## Error which has information
### recover_fund
- Not known that it's an error but it returns full raw_result and at current code, that full raw_result is shown even if it's sucess, so it's okay.

## Error which has no information
### retrieve_seed
- ??? I think this returns "wrong password" when there is a true error ???
- String "wrong password" when derive password fails
- String "wrong password" when corrupted file or wrong password
### login
- ??? I think this returns "false" when there is a true error ???
- Boolean false when derive_password_failed
- Boolean false when corrupted_file_or_wrong_password
### prepare_send
- ??? Potential problem here ???
- Returns object
- withdraw function call inside sets error field of the object with constant string: "Not enough funds to cover txfee, please reduce amount." if raw_result has "Not sufficient balance. Couldn't collect enough value from utxos" in it. 
- All other errors in withdraw function are ignored because they set "ec" variable but that's not inside the return object of prepare_send
### prepare_send_fees
- ??? Potential problem here ???
- Returns object
- withdraw function call inside sets error field of the object with constant string: "Not enough funds to cover txfee, please reduce amount." if raw_result has "Not sufficient balance. Couldn't collect enough value from utxos" in it. 
- All other errors in withdraw function are ignored because they set "ec" variable but that's not inside the return object of prepare_send_fees
### place_sell_order
- ??? Potential problem here ???
- There are multiple errors but they all squished into a boolean
### place_buy_order
- ??? Potential problem here ???
- There are multiple errors but they all squished into a boolean
### get_orderbook
- ??? Potential problem here ???
- Returns empty {} in all error cases
### disconnect
- Boolean value, returns false only if deleting a file fails
### delete_wallet
- Boolean value, returns false only if deleting a file fails
### create
- Boolean false when derive_password_failed
### claim_rewards
- Returns {} if ticker_is_not_claimable or claim_not_enough_funds

# Does not have error
### enable_coins
- ??? This might not be healthy ???
- Always returns true
### disable_coins
- ??? This might not be healthy ???
- Always returns false
### send
- ??? Is it possible that mm2 fails at send ???
- String value: tx_hash
### send_rewards
- ??? Is it possible that mm2 fails at send ???
- String value: tx_hash
### get_my_orders
- No error in answer, order_not_available_yet returns {}
### cancel_order
- Void because it's async
### cancel_all_orders
- Void because it's async
### cancel_all_orders_by_ticker
- Void because it's async
### get_available_langs
- String list value
### to_eth_checksum_qt
- String value
### get_log_folder
- String value
### get_mm2_version
- String value
### get_version
- String value
### get_portfolio_informations
- Object array value
### get_price_amount
- String value
### get_coin_info
- Object value, {} if not found
### first_run
- Boolean value
### get_mnemonic
- String value
### mnemonic_validate
- Boolean value
### is_there_a_default_wallet
- Boolean value
### do_i_have_enough_funds
- Boolean value
### get_balance
- String value, 0 if not coin is not enabled
### is_claiming_ready
- Boolean value
### set_current_orderbook
- Void
### on_gui_enter_dex
- Void
### on_gui_leave_dex
- Void
### change_state
- Void
### get_recent_swaps
- Object value
### refresh_infos
- Void and async
### refresh_orders_and_swaps
- Void and async
### get_wallets
- String list value
### get_trade_infos
- Object value

**Comment by Milerius** [comment]
Most of them are now showed in the UI when required, otherwise it's hide for the user.
