### ISSUE TITLE
Incoming Funds not available in the DEX section

### ISSUE THREAD

**Issue by teedan** [KomodoPlatform/atomicDEX-Desktop#470]
Repro:
- create a new, empty wallet in atomicDEX pro, all balances are zero
- activate KMD and BTC coins
- go to the dex tab. You can't exchange since you don't have funds.
- send BTC or KMD to the wallet and let it confirm

--> In the DEX section, the funds do not appear. So even though you have funds, you cannot start a swap or create an order. Only a restart of the app solves the problem.

**Comment by tonymorony** [comment]
Hi @garnon , thank you for opening the issue. Moved from API to GUI repo.

Which application version and OS are you using?

This issue sounds pretty similar to https://github.com/KomodoPlatform/atomicDEX-Pro/issues/469

**Comment by garnon** [comment]
I'm using atomicDeFi Pro v0.2.1-alpha on Windows 10 64 bit.

**Comment by barbierir** [comment]
I think to have the same (or a similar) issue on Ubuntu, the balance of KMD and other coins don't longer update in the 'dashboard' and 'wallet' tabs after a few days of the app running. The balances updated normally the first 2 days, then they stopped. The app is working in background because I can still claim the reward (I see from online explorer) and do swap (the dex tab works) so it's a gui thing

**Comment by tonymorony** [comment]
Thank you for reports! Multiple places with balances receiving were reworked after 0.2.1, we'll track that this issue will not persists in the next release

**Comment by Milerius** [comment]
this works now
