### ISSUE TITLE
[BUG]: Min trade balance on order selection works not correct

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Desktop#746]
the right part of the orderbook doesn't require any KMD for trade (it's MCL buy orders - I can sell MCL into it for KMD)

<img width="1440" alt="Screenshot 2021-03-16 at 03 30 30" src="https://user-images.githubusercontent.com/24797699/111217498-31e6c600-8608-11eb-9059-b196ebfad86c.png">
<img width="1440" alt="Screenshot 2021-03-16 at 03 30 26" src="https://user-images.githubusercontent.com/24797699/111217514-36ab7a00-8608-11eb-8d19-15fe305aab90.png">

interesting that when I switch it from KMD-MCL to MCL-KMD it's not detecting both parts, however, I can't buy any MCL (should be an error for the right part). Please review that validation since it works not correct for almost all cases now (also keep in mind cases of ETH/ERC gas fee):

<img width="1440" alt="Screenshot 2021-03-16 at 03 34 35" src="https://user-images.githubusercontent.com/24797699/111217824-9144d600-8608-11eb-923d-243996f5db32.png">

<img width="1440" alt="Screenshot 2021-03-16 at 03 34 32" src="https://user-images.githubusercontent.com/24797699/111217800-8d18b880-8608-11eb-985c-c7f6c9560051.png">

**Comment by Milerius** [comment]
Thanks for opening the issue @tonymorony - as mentioned by @SylEze in another issue, this concerns #726 pr, would be nice to comment directly in this PR since it's still a `draft`, i'm aware of the current issue, but we were waiting for the `rel_volume` fields in order to solve this PB, we are finishing best orders now and we already knows how to fix this problem.

**Comment by smk762** [comment]
looks good in https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/726
