### ISSUE TITLE
[BUG]:  Chart YTD is not working

### ISSUE THREAD

**Issue by Milerius** [KomodoPlatform/atomicDEX-Desktop#789]
**Describe the bug**

YTD means all the data points for each day since the beginning of the year, at the current stage it is over 90, and it is getting worse by the day, please find a solution to make the chart visible / user-friendly

**To Reproduce**
1. Go to 'Portfolio Page'
2. Click on 'YTD'
3. Observe the chart.
4. Does it feel correct / user-friendly ?

**Actual behavior**

https://user-images.githubusercontent.com/21139416/114446568-ab56e180-9bd1-11eb-8d64-479a40ee209e.mov

**Expected behavior**

https://user-images.githubusercontent.com/21139416/114446193-3edbe280-9bd1-11eb-95c5-eb159ba3346d.mov

**Screenshots**

<img width="750" alt="Capture d’écran 2021-04-12 à 20 46 05" src="https://user-images.githubusercontent.com/21139416/114445741-b8bf9c00-9bd0-11eb-8ad5-7588a09c2ef0.png">

**Desktop (please complete the following information):**
 - OS: MacOS / Windows / Linux
 - Version 0.4.0

**Additional context**

Portfolio features

**Comment by tonymorony** [comment]
Please note that we can't release 0.5.0 with a widget stating "work in progress" because 0.5.0 is a milestone and it's blocker. So we'll need to decide if we have time to make it working properly until the release or temporarily remove it entirely and stick to initial design proposal with portfolio circle in the middle.
