### ISSUE TITLE
[BUG]: length of volume bars is wrong

### ISSUE THREAD

**Issue by cipig** [KomodoPlatform/atomicDEX-Desktop#858]
![image](https://user-images.githubusercontent.com/32116761/115989069-ff879b80-a5ab-11eb-8096-126624c4b8b0.png)
see on the right

**Comment by ssakone** [comment]
@cipig its only for pair VRSC & KMD or all?

**Comment by cipig** [comment]
![image](https://user-images.githubusercontent.com/32116761/116673630-29b5d080-a993-11eb-88b8-bea284490dd4.png)
happens on MCL/KMD too... it seems related to the number of entries in the orderbook, couldn't reproduce on pairs with only few orders

**Comment by cipig** [comment]
![image](https://user-images.githubusercontent.com/32116761/116678663-19a0ef80-a999-11eb-9fdf-fb283f2f1f12.png)
also, the length of the bars are determined only by the volume of one side of orderbook (bid or ask), not accross... the volume on the left is much bigger than that on the right, but the bars do not reflect that

**Comment by smk762** [comment]
Bar length appears to correlate with quantity in https://github.com/KomodoPlatform/atomicDEX-Desktop/commit/43f74b38a5b58b17310d731c9a8763fc54ec7930

![image](https://user-images.githubusercontent.com/35845239/122671528-b2195a80-d1f9-11eb-9201-74cdf56717af.png)

Lengths are relative to highest qty on either sell or buy side (not both) - not sure if this is intentional or if being relative to max value of both buy and sell would be preferred. 

For comparison on Binance, the same Qty value on buy or sell side is same length. 
![image](https://user-images.githubusercontent.com/35845239/122671601-13412e00-d1fa-11eb-9639-cfc6229311ad.png)

Full length bar appears to be `if Qty >  average_qty_on_both_buy_and_sell` (not 100% sure, but looks around there)
Then bar length for the rest would be `Qty / average_qty_on_both_buy_and_sell`

i.e.
```
if qty > average:
    bar = 100
else:
    bar = qty / average * 100
```

**Comment by cipig** [comment]
the bug happens after an orderbook update
the initial length of bars is correct when you first switch to the pair, but is totally off after updates
![image](https://user-images.githubusercontent.com/32116761/146641183-8e46655b-63c8-45c7-b785-11ed5913af40.png)

**Comment by tonymorony** [comment]
@cipig thank you for the update! we'll have a look at it and fix in the next split as a part of https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1463 task
